// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Card: typeof import('./src/components/Card.vue')['default']
    CardArea: typeof import('./src/components/process/CardArea.vue')['default']
    EnemyArea: typeof import('./src/components/process/EnemyArea.vue')['default']
    EnemyPlayer: typeof import('./src/components/process/EnemyPlayer.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Stage: typeof import('./src/components/process/Stage.vue')['default']
  }
}

export {}
